common:
  seed: 123
  cuda_devices: [0]
  num_saved_checkpoints: 3

data:
  data_class: ShapeNet
  data_class_kwargs:
    norm: true
    radius: false

  task_type: 'segmentation'
  target: 'instance miou'
  pre_transforms:
    - UnitSphere()

model:
  net_arguments:
    use_xyz: true
    input_channels: 0  # feature channels except (x, y, z)
    relation_prior: 1

  criterion:
    - class: CrossEntropyLoss
      weight: 1

training:
  batch_size: 28
  num_workers: 4
  transforms:
    - FixedPoints(2048)

  num_epoches: 200

  optimizer: Adam
  optimizer_kwargs:
    lr: 0.001
    weight_decay: 0

  scheduler: LambdaLR
  scheduler_kwargs:
    lr_lambda: 'lambda e: max(0.5**(e // 21), 0.00001 / 0.001)'

testing:
  batch_size: 28
  num_workers: 4
  transforms:
    - FixedPoints(2048)