common:
  seed: 666
  cuda_devices: [0]
  num_saved_checkpoints: 3

data:
  data_class: ShapeNet
  data_class_kwargs:
    norm: true
    radius: false

  task_type: 'segmentation'
  target: 'instance miou'
  pre_transforms:
    - UnitSphere()

model:
  net_arguments:
    norm_type: bn
    num_neighbors: 16
    dilation: 1
    num_interpolation_neighbors: 3

  criterion:
    - class: CrossEntropyLoss
      weight: 1
      kwargs:
        label_smoothing: 0.2

training:
  batch_size: 16
  num_workers: 4
  transforms:
    - FixedPoints(1024)
    - ScalePoints((2./3., 3./2.))
    - Jitter()

  num_epoches: 200

  optimizer: SGD
  optimizer_kwargs:
    lr: 0.05
    momentum: 0.9
    weight_decay: 0.0001

  scheduler: LambdaLR
  scheduler_kwargs:
    lr_lambda: 'lambda e: (1, 0.1)[e >= 120] * (1, 0.1)[e >= 160]'

testing:
  batch_size: 16
  num_workers: 4
  transforms:
    - FixedPoints(1024)