common:
  seed: 666
  cuda_devices: [0]
  num_saved_checkpoints: 3

data:
  data_class: ShapeNet
  data_class_kwargs:
    norm: true
    radius: false

  task_type: segmentation
  target: instance miou
  pre_transforms:
    - UnitSphere()

model:
  net_arguments:
    points: 2048

  criterion:
    - class: CrossEntropyLoss
      weight: 1

training:
  batch_size: 32
  num_workers: 12
  transforms:
    - ShufflePoints()
    - ChunkPoints(2048)

  num_epoches: 350

  optimizer: Adam
  optimizer_kwargs:
    lr: 0.003
    betas:
      - 0.9
      - 0.999
    eps: 0.00000001
    weight_decay: 0

  scheduler: StepLR
  scheduler_kwargs:
    step_size: 40
    gamma: 0.5

testing:
  batch_size: 32
  num_workers: 4
  transforms:
    - ChunkPoints(2048)