common:
  seed: 666
  cuda_devices: [0]
  num_saved_checkpoints: 3

data:
  data_class: ShapeNet
  data_class_kwargs:
    norm: true
    radius: false

  task_type: segmentation
  target: instance miou
  pre_transforms:
    - UnitSphere()

model:
  net_arguments:
    points: 2048

  criterion:
    - class: CrossEntropyLoss
      weight: 1

training:
  batch_size: 32
  num_workers: 4
  transforms:
    - FixedPoints(2048)
    - ScalePoints((0.67, 1.5))

  num_epoches: 300

  optimizer: SGD
  optimizer_kwargs:
    lr: 0.05
    momentum: 0.9
    weight_decay: 0.0001

  scheduler: LambdaLR
  scheduler_kwargs:
    lr_lambda: 'lambda e: (1, 0.1)[e >= 120] * (1, 0.1)[e >= 160]'

testing:
  batch_size: 32
  num_workers: 4
  transforms:
    - FixedPoints(2048)